### PR TITLE
saasbook/hw-style skeleton, placeholders, and initial Mvp spec

### PR DESCRIPTION
**Pull request by apelade**
- added directory structure similar to saasbook/hw including placeholders for READMEs
- autograder test spec file
- feature that tests it
- install feature duped from saasbook/hw

still need to add travis file and eliminate dependency on my personal gitimmersion repo in username.txt, possibly git --local

### CODE REVIEW

**Comment by tansaku** [comment]
thanks, is this pull request based on Richard V.s? or superseding it?

**Comment by apelade** [comment]
Superseding, unfortunately. I hadn't understood we were making a public
version of the whole hw repo with one github rspec gradable hw. Only the
middle commit is strictly necessary, but added the last so they would not
be mystified. It adds in the rag install.
It needs more things like the XML file to run vs edx if that is the plan?

**Comment by apelade** [comment]
You could cherry-pick just the middle commit. Especially now that saasbook/rag master branch works, all we would need to do is put in the error message and/or documentation that they need to manually clone rag inside it.

**Comment by apelade** [comment]
Will be redoing pull request as discussed offline.

**Pull request closed without merging**
