### PR TITLE
add oauth for 5000/hr github rate limit

### PR DESCRIPTION
**Pull request by apelade**
- it's using my api key, should be AV, or even student key with a change to the grader 
- changed START_DATE to Date.today << 12, is that OK? Need to be string?
- commented-out check for  c.author.login in case they start with one id on local and use different name on github

### CODE REVIEW

**Comment by apelade** [comment]
I removed a bunch of commented out code in the last commit. It's still available in github if we want to resurrect it. On thing in particular:

```
# Can't assert these because Students may have commits locally under different
# name than github username, eg 'saasbook' add test repo for that case
#@commits.each {|c| c.author.login.should eq ENV['GITHUB_USERNAME']} 
```

**Comment by tansaku** [comment]
great, yes, wasn't expecting you to put your api key in the actual pull request :-) just get it working locally and then we would talk about how to encrypt the API key into the travis.yml file ...

What I can update your comments?! Man you were hacked!

**Comment by apelade** [comment]
No prob, that key can only fetch public info and we can revoke it, or assume the hub will if there's an issue..

**Comment by apelade** [comment]
Added the ecrypted github key. Can't see how to generate one for the organization, only personal yet.

**Pull request merged**
